[workspace]

resolver = "2"
members = [
  "analysis",
  "bril-driver",
  "bril-lib",
  "transform-driver",
  "transform-lib",
  "utils",
]
exclude = [
  "transform-parser-fuzz"
]

[workspace.lints.clippy]
doc_lazy_continuation = "allow"
