[workspace]

resolver = "2"
members = [
  "analysis",
  "bril-driver",
  "bril-lib",
  "transform-driver",
  "transform-lib",
  "utils",
]
exclude = [
  "transform-parser-fuzz"
]

[patch.crates-io]
number-theory = { git = 'https://github.com/JASory/ENT.git' }
