[package]
name = "parser-fuzz"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "*"
domains-lib = { path = "../domains-lib"}
utils = { path = "../utils"}