name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install system packages
      run: sudo apt-get install libglib2.0-dev libcairo2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Lint
      run: cargo clippy --verbose --all-features -- -D warnings
    - name: Docs
      run: cargo doc --no-deps --all-features
